spring:
  profiles:
    active: development
---
spring:
  profiles: development
  application:
    name: online-store-web
zuul:
  ignored-services: '*'
  routes:
    edge-service: /api/**
    auth-service:
      path: /user/**
      url: http://116.56.140.66:8181/uaa/v1/me
edge-service:
  ribbon:
    listOfServers: http://116.56.140.66:9999
security:
  enable-csrf: false
  oauth2:
    resource:
      userInfoUri: http://116.56.140.66:8181/uaa/user
    client:
      accessTokenUri: http://116.56.140.66:8181/uaa/oauth/token
      userAuthorizationUri: http://116.56.140.66:8181/uaa/oauth/authorize
      clientId: acme
      clientSecret: acmesecret
  ignored: /assets/**,/catalog/**